FROM golang:1.19-alpine3.15

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

# 修正 CVE 通報資安漏洞
RUN sed -i 's/v3.15/v3.16/g' /etc/apk/repositories \
    && apk update \
    && apk upgrade

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && \
    chmod -R 777 "$GOPATH" && \
    apk add --no-cache gcc musl-dev && \
    apk add git && \
    apk update && \
    apk upgrade 

# RUN go version
ADD . $GOPATH/src/app

WORKDIR $GOPATH/src/app

RUN git config --global url."https://mathdeploy:cy7esPtgCq5ox7uMg55s@gitlab.com/gaas_math/".insteadOf "https://gitlab.com/gaas_math/"
RUN git config --global url."https://mathdeploy:32SqNB_-_mssqxNXsfyw@gitlab.com/gaas_module/".insteadOf "https://gitlab.com/gaas_module/"


# docker build
RUN go mod tidy
RUN go build $GOPATH/src/app/app.go

RUN apk del git && \
    rm -rf $GOPATH/src/github.com/

EXPOSE 80
CMD ./app

